package com.carelog.core

/**
 * Build configuration constants.
 * Note: This is a placeholder. The actual BuildConfig is generated by Gradle.
 */
object BuildConfig {
    const val DEBUG = true
    const val APPLICATION_ID = "com.carelog"
    const val BUILD_TYPE = "debug"
    const val VERSION_CODE = 4
    const val VERSION_NAME = "1.3.0"
    const val API_BASE_URL = "https://x6v72ekrcl.execute-api.ap-south-1.amazonaws.com/dev"
}
